// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartSystem.Data;

#nullable disable

namespace SmartSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260220205156_AdicionandoNovosCampos")]
    partial class AdicionandoNovosCampos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EnderecoClientesEntrega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CEP")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "postalCode");

                    b.Property<string>("Cidade")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "city");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "clienteId");

                    b.Property<string>("Complemento")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "complement");

                    b.Property<string>("Endereco")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "address");

                    b.Property<string>("Estado")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "state");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "firstName");

                    b.Property<string>("Pais")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "country");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "lastName");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "phone");

                    b.HasKey("Id");

                    b.ToTable("EnderecoClientes");
                });

            modelBuilder.Entity("SmartSystem.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
